### ISSUE TITLE
在1.16.5版本的Arclight服务端使用时无法启动服务器

### ISSUE THREAD

**Issue by TakanashiRi** [majongMC/Minecraft-Breath-Of-The-Wild-Mod#2]
[latest.log](https://github.com/majongMC/Minecraft-Breath-Of-The-Wild-Mod/files/9145860/latest.log)

**Comment by majongMC** [comment]
问题已收到，感谢您的反馈
目前1.16.5的Gradle文件在构建1.19环境的时候损坏了，该版本目前在短时间内不方便修复
我会尝试在1.19的版本中修复这个问题
到时候建议您用1.19的版本再试一下

**Comment by majongMC** [comment]
目前所有版本都经过了服务端测试，可以正常在服务器上运行
